name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag base-ubuntu:$(date +%s)
    - name: Login to JFrog
      uses: docker/login-action@v1
      with:
        registry: hchiao1.jfrog.io
        username: ${{ secrets.JFROG_USER_WRITER }}
        password: ${{ secrets.JFROG_PASSWORD_WRITER }}
    - name: Build and push 
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: hchiao1.jfrog.io/docker/base-ubuntu:latest
    - name: create pull request
      run: gh pr create -B dev -H main --title 'Merge dev into main' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    